/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Traitimg.h"

bool_t
xdr_image_t(XDR *xdrs,
            image_t *objp)

{
	int32_t *buf;

	if (xdrs->x_op == XDR_ENCODE) {
		buf = (int32_t *)XDR_INLINE(xdrs, (4 + 2500) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->LargImage))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->HautImage))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->n_pixels))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->m_pixels))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->img, 2500, sizeof(int), (xdrproc_t)xdr_int))
				return (FALSE);
		} else {
			IXDR_PUT_LONG(buf, objp->LargImage);
			IXDR_PUT_LONG(buf, objp->HautImage);
			IXDR_PUT_LONG(buf, objp->n_pixels);
			IXDR_PUT_LONG(buf, objp->m_pixels);
			{
				int i;
				int *genp;

				for (i = 0, genp = objp->img;
				    i < 2500; i++) {
					IXDR_PUT_LONG(buf, *genp++);
				}
			}
		}
	} else if (xdrs->x_op == XDR_DECODE) {
		buf = (int32_t *)XDR_INLINE(xdrs, (4 + 2500) * BYTES_PER_XDR_UNIT);
		if (buf == NULL) {
			if (!xdr_int(xdrs, &objp->LargImage))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->HautImage))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->n_pixels))
				return (FALSE);
			if (!xdr_int(xdrs, &objp->m_pixels))
				return (FALSE);
			if (!xdr_vector(xdrs, (char *)objp->img, 2500, sizeof(int), (xdrproc_t)xdr_int))
				return (FALSE);
		} else {
			objp->LargImage = IXDR_GET_LONG(buf);
			objp->HautImage = IXDR_GET_LONG(buf);
			objp->n_pixels = IXDR_GET_LONG(buf);
			objp->m_pixels = IXDR_GET_LONG(buf);
			{
				int i;
				int *genp;

				for (i = 0, genp = objp->img;
				    i < 2500; i++) {
					*genp++ = IXDR_GET_LONG(buf);
				}
			}
		}
	} else {
		if (!xdr_int(xdrs, &objp->LargImage))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->HautImage))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->n_pixels))
			return (FALSE);
		if (!xdr_int(xdrs, &objp->m_pixels))
			return (FALSE);
		if (!xdr_vector(xdrs, (char *)objp->img, 2500, sizeof(int), (xdrproc_t)xdr_int))
			return (FALSE);
	}
	return (TRUE);
}
