/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRAITIMG_H_RPCGEN
#define _TRAITIMG_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct image_t {
	int LargImage;
	int HautImage;
	int n_pixels;
	int m_pixels;
	int img[2500];
};
typedef struct image_t image_t;
#ifdef __cplusplus
extern "C" bool_t xdr_image_t(XDR *, image_t*);
#elif __STDC__
extern  bool_t xdr_image_t(XDR *, image_t*);
#else /* Old Style C */
bool_t xdr_image_t();
#endif /* Old Style C */


#define FILTERPROG ((rpc_uint)0x02000006)
#define FILTERVERS ((rpc_uint)1)

#ifdef __cplusplus
#define filtre_moyenne ((rpc_uint)1)
extern "C" image_t * filtre_moyenne_1(image_t *, CLIENT *);
extern "C" image_t * filtre_moyenne_1_svc(image_t *, struct svc_req *);
#define filtre_median ((rpc_uint)2)
extern "C" image_t * filtre_median_1(image_t *, CLIENT *);
extern "C" image_t * filtre_median_1_svc(image_t *, struct svc_req *);
#define histogramme ((rpc_uint)3)
extern "C" image_t * histogramme_1(image_t *, CLIENT *);
extern "C" image_t * histogramme_1_svc(image_t *, struct svc_req *);

#elif __STDC__
#define filtre_moyenne ((rpc_uint)1)
extern  image_t * filtre_moyenne_1(image_t *, CLIENT *);
extern  image_t * filtre_moyenne_1_svc(image_t *, struct svc_req *);
#define filtre_median ((rpc_uint)2)
extern  image_t * filtre_median_1(image_t *, CLIENT *);
extern  image_t * filtre_median_1_svc(image_t *, struct svc_req *);
#define histogramme ((rpc_uint)3)
extern  image_t * histogramme_1(image_t *, CLIENT *);
extern  image_t * histogramme_1_svc(image_t *, struct svc_req *);

#else /* Old Style C */
#define filtre_moyenne ((rpc_uint)1)
extern  image_t * filtre_moyenne_1();
extern  image_t * filtre_moyenne_1_svc();
#define filtre_median ((rpc_uint)2)
extern  image_t * filtre_median_1();
extern  image_t * filtre_median_1_svc();
#define histogramme ((rpc_uint)3)
extern  image_t * histogramme_1();
extern  image_t * histogramme_1_svc();
#endif /* Old Style C */

#endif /* !_TRAITIMG_H_RPCGEN */
