/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Traitimg.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
static int compare (void const *a, void const *b)
{

    int const *pa = a;
    int const *pb = b;
    return *pa - *pb;
}

image_t *
filtre_median_1_svc(image_t *argp, struct svc_req *rqstp)
{
    static image_t result;
    int mult =((argp->LargImage)*(argp->HautImage));
    int i = 0;
    memcpy (result.img, argp->img, mult*sizeof(int)); /*On copie dans les valeurs de argp->img dans result.img*/
    qsort(argp->img,mult,sizeof(int),compare);
    if(mult>=9){
        for(i=4;i<mult;i=i+9){
            result.img[i]=argp->img[i];
        }
    }
    
    return &result;
}

image_t *
filtre_moyenne_1_svc(image_t *argp, struct svc_req *rqstp)
{
    static image_t result;
    int mult =((argp->LargImage)*(argp->HautImage));
    int i = 0;
    memcpy (result.img, argp->img, mult*sizeof(int)); /*On copie dans les valeurs de argp->img dans result.img*/
    if(mult>=9){
        for(i=4;i<mult;i=i+9){
            result.img[i]=(result.img[i]+result.img[i-1] + result.img[i-2] +result.img[i-3] + result.img[i-4] + result.img[i+1] + result.img[i+2] + result.img[i+3] + result.img[i+4])/9;
        }
    }
    return &result;
}


image_t *
histogramme_1_svc(image_t *argp, struct svc_req *rqstp)
{
    static image_t  result;
    int i;
    for(i=0;i<((argp->LargImage)*(argp->HautImage));i++){
        result.img[i]=0;
    }
    for(i=0;i<((argp->LargImage)*(argp->HautImage));i++){
        result.img[argp->img[i]]+=1;
    }
    return &result;
}



