/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "Traitimg.h"
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include <time.h>

void
filterprog_1(host)
char *host;
{
	CLIENT *clnt;
	image_t  *result_1;
	image_t  filtre_moyenne_1_arg;
	image_t  *result_2;
	image_t  filtre_median_1_arg;
	image_t  *result_3;
	image_t  histogramme_1_arg;
    
    image_t image;
    srand(time(NULL));
    printf("Quelle est la largeur de l'image : ");
    scanf("%i",&(image.LargImage));
    printf("Quelle est la hauteur de l'image : ");
    scanf("%i",&(image.HautImage));
    int i,j;
    for(i=0;i<2500;i++){
        image.img[i]=0;
    }
    printf("\nMatrice de base\n");
    for(i=0;i<image.HautImage*image.LargImage;i++){
        image.img[i]=rand()%255;
        printf("%i ",image.img[i]);
    }
	clnt = clnt_create(host, FILTERPROG, FILTERVERS, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror(host);
		exit(1);
	}
	result_1 = filtre_moyenne_1(&image, clnt);
	if (result_1 == NULL) {
		clnt_perror(clnt, "call failed:");
	}
    else{
        printf("\nMatrice avec filtre Moyenne\n");
        
        for(i=0;i<(image.HautImage*image.LargImage);i++){
                printf("%i ",result_1->img[i]);
        }
        printf("\n");
    }
	result_2 = filtre_median_1(&image, clnt);
	if (result_2 == NULL) {
		clnt_perror(clnt, "call failed:");
    }else{
        printf("\nMatrice avec filtre median\n");
        
        for(i=0;i<(image.HautImage*image.LargImage);i++){
            printf("%i ",result_2->img[i]);
        }
        printf("\n");
    }
	result_3 = histogramme_1(&image, clnt);
	if (result_3 == NULL) {
		clnt_perror(clnt, "call failed:");
    }else{
        printf("\nHistorigramme\n");
        
        for(i=0;i<255;i++){
            if(result_3->img[i]>0)printf("%i : %i \n",i,result_3->img[i]);
        }
        printf("\n");
    }
	clnt_destroy( clnt );
}


int main(int argc,char *argv[])

{
	char *host;

	if(argc < 2) {
		printf("usage: %s server_host\n", argv[0]);
		exit(1);
	}
	host = argv[1];
	filterprog_1( host );
}
