/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "Traitimg.h"

/* Default timeout can be changed using clnt_control() */
static struct timeval TIMEOUT = { 25, 0 };

image_t *
filtre_moyenne_1(image_t *argp,
                 CLIENT *clnt)

{
	static image_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, filtre_moyenne, xdr_image_t, argp, xdr_image_t, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

image_t *
filtre_median_1(image_t *argp,
                CLIENT *clnt)
{
	static image_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, filtre_median, xdr_image_t, argp, xdr_image_t, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}

image_t *
histogramme_1(image_t *argp,
              CLIENT *clnt)
{
	static image_t clnt_res;

	memset((char *)&clnt_res, 0, sizeof(clnt_res));
	if (clnt_call(clnt, histogramme, xdr_image_t, argp, xdr_image_t, &clnt_res, TIMEOUT) != RPC_SUCCESS)
		return (NULL);
	return (&clnt_res);
}
